# Generated by Django 4.2 on 2023-04-21 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="address",),
        migrations.AddField(
            model_name="address",
            name="resident",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
