# Generated by Django 4.2 on 2023-04-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_orderitem_product_alter_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.orderitem",
            ),
        ),
    ]
