# Generated by Django 4.2 on 2023-04-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="paid", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="order_items",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.orderitem",
            ),
        ),
    ]
