# Generated by Django 4.2 on 2023-04-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_order_paid_orderitem_paid_alter_user_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=20),
        ),
    ]
